services:
  # PostgreSQL 17 Database
  postgres:
    image: postgres:17-alpine
    container_name: golden-palace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: golden_palace_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - golden-palace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d golden_palace_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 7 for Caching and Sessions
  redis:
    image: redis:7-alpine
    container_name: golden-palace-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./infrastructure/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - golden-palace-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Adminer for Database Management (Development Only)
  adminer:
    image: adminer:4.8.1
    container_name: golden-palace-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    networks:
      - golden-palace-network
    depends_on:
      postgres:
        condition: service_healthy

  # Redis Commander for Redis Management (Development Only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: golden-palace-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    networks:
      - golden-palace-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  golden-palace-network:
    driver: bridge
